//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstralBattles.Localizations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstralBattles.Localizations.CommonResources", typeof(CommonResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is a mobile version of the famous desktop game Spectromancer. All cards&apos; texts are copyright (c) Three Donkeys LLC. You may also contact me via jabber at main@conference.jabber.uruchie.org.
        /// </summary>
        internal static string AboutBody {
            get {
                return ResourceManager.GetString("AboutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beasts.
        /// </summary>
        internal static string Beast {
            get {
                return ResourceManager.GetString("Beast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        internal static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign mode.
        /// </summary>
        internal static string CampaignTip {
            get {
                return ResourceManager.GetString("CampaignTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is casting {1}.
        /// </summary>
        internal static string Casting {
            get {
                return ResourceManager.GetString("Casting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos.
        /// </summary>
        internal static string Chaos {
            get {
                return ResourceManager.GetString("Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure deck.
        /// </summary>
        internal static string ConfigureDeck {
            get {
                return ResourceManager.GetString("ConfigureDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you have finished the Tournament on the {0} place. Thanks for playing and wait for Astral Battles 2 with campaign and online multiplayer!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue started campaign.
        /// </summary>
        internal static string ContinueCampaignTip {
            get {
                return ResourceManager.GetString("ContinueCampaignTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue the current game.
        /// </summary>
        internal static string ContinueTip {
            get {
                return ResourceManager.GetString("ContinueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue last played tournament game.
        /// </summary>
        internal static string ContinueTournamentTip {
            get {
                return ResourceManager.GetString("ContinueTournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2011 Egor Bogatov.
        /// </summary>
        internal static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} creature, attack: {1}, Health: {2}, cost: {3}..
        /// </summary>
        internal static string CreatureShortDesc {
            get {
                return ResourceManager.GetString("CreatureShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack: {0}, Health: {1}, Cost: {2}..
        /// </summary>
        internal static string CreatureShortDesc2 {
            get {
                return ResourceManager.GetString("CreatureShortDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tournament will be overwritten..
        /// </summary>
        internal static string CurrentTournamentWillBeOverwritten {
            get {
                return ResourceManager.GetString("CurrentTournamentWillBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death.
        /// </summary>
        internal static string Death {
            get {
                return ResourceManager.GetString("Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonics.
        /// </summary>
        internal static string Demonic {
            get {
                return ResourceManager.GetString("Demonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        internal static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face selection.
        /// </summary>
        internal static string FaceSelection {
            get {
                return ResourceManager.GetString("FaceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th element:.
        /// </summary>
        internal static string FifthElement {
            get {
                return ResourceManager.GetString("FifthElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last played game will be overwritten..
        /// </summary>
        internal static string GameWillBeOverwritten {
            get {
                return ResourceManager.GetString("GameWillBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goblins.
        /// </summary>
        internal static string Goblins {
            get {
                return ResourceManager.GetString("Goblins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has casted a {1} spell.
        /// </summary>
        internal static string HasCasted {
            get {
                return ResourceManager.GetString("HasCasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has skipped his turn.
        /// </summary>
        internal static string HasSkipped {
            get {
                return ResourceManager.GetString("HasSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has summoned a {1}.
        /// </summary>
        internal static string HasSummoned {
            get {
                return ResourceManager.GetString("HasSummoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has won!.
        /// </summary>
        internal static string HasWon {
            get {
                return ResourceManager.GetString("HasWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * German and French are coming soon.
        /// </summary>
        internal static string HelpImproveLanguages {
            get {
                return ResourceManager.GetString("HelpImproveLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy.
        /// </summary>
        internal static string Holy {
            get {
                return ResourceManager.GetString("Holy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host a server.
        /// </summary>
        internal static string HostAServer {
            get {
                return ResourceManager.GetString("HostAServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host a server for playing duel.
        /// </summary>
        internal static string HostAServerTip {
            get {
                return ResourceManager.GetString("HostAServerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion.
        /// </summary>
        internal static string Illusion {
            get {
                return ResourceManager.GetString("Illusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is computer (A.I.).
        /// </summary>
        internal static string IsComputer {
            get {
                return ResourceManager.GetString("IsComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to server.
        /// </summary>
        internal static string JoinToServer {
            get {
                return ResourceManager.GetString("JoinToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to server by IP.
        /// </summary>
        internal static string JoinToServerTip {
            get {
                return ResourceManager.GetString("JoinToServerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the last hosted game.
        /// </summary>
        internal static string LoadGame {
            get {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the last hosted game as a server.
        /// </summary>
        internal static string LoadGameTip {
            get {
                return ResourceManager.GetString("LoadGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanics.
        /// </summary>
        internal static string Mechanical {
            get {
                return ResourceManager.GetString("Mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names shouldn&apos;t be empty.
        /// </summary>
        internal static string NamesShouldBeNotEmptyMessage {
            get {
                return ResourceManager.GetString("NamesShouldBeNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names should be unique.
        /// </summary>
        internal static string NamesShouldBeNotEqualMessage {
            get {
                return ResourceManager.GetString("NamesShouldBeNotEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New campaign.
        /// </summary>
        internal static string NewCampaign {
            get {
                return ResourceManager.GetString("NewCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new campaign.
        /// </summary>
        internal static string NewCampaignTip {
            get {
                return ResourceManager.GetString("NewCampaignTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new game for 2 players.
        /// </summary>
        internal static string NewGameTip {
            get {
                return ResourceManager.GetString("NewGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tournament.
        /// </summary>
        internal static string NewTournament {
            get {
                return ResourceManager.GetString("NewTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the new tournament.
        /// </summary>
        internal static string NewTournamentTip {
            get {
                return ResourceManager.GetString("NewTournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next game.
        /// </summary>
        internal static string NextGame {
            get {
                return ResourceManager.GetString("NextGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next turn.
        /// </summary>
        internal static string NextTurn {
            get {
                return ResourceManager.GetString("NextTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, it&apos;s your turn!.
        /// </summary>
        internal static string NextTurnMessage {
            get {
                return ResourceManager.GetString("NextTurnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot seat mode.
        /// </summary>
        internal static string OnOneDevice {
            get {
                return ResourceManager.GetString("OnOneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a duel on the single device.
        /// </summary>
        internal static string OnOneDeviceTip {
            get {
                return ResourceManager.GetString("OnOneDeviceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 1 name:.
        /// </summary>
        internal static string Player1NameLabel {
            get {
                return ResourceManager.GetString("Player1NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 2 name:.
        /// </summary>
        internal static string Player2NameLabel {
            get {
                return ResourceManager.GetString("Player2NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s name:.
        /// </summary>
        internal static string PlayersName {
            get {
                return ResourceManager.GetString("PlayersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resort.
        /// </summary>
        internal static string Resort {
            get {
                return ResourceManager.GetString("Resort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review game.
        /// </summary>
        internal static string ReviewGame {
            get {
                return ResourceManager.GetString("ReviewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round {0} has been started.
        /// </summary>
        internal static string RoundStarted {
            get {
                return ResourceManager.GetString("RoundStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        internal static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcery.
        /// </summary>
        internal static string Sorcery {
            get {
                return ResourceManager.GetString("Sorcery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        internal static string Spec_Druid {
            get {
                return ResourceManager.GetString("Spec_Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player recieves +2 bonus to his earth element power and gains +1 health each round. Additional cards: Master healer, Stone rain.
        /// </summary>
        internal static string Spec_DruidTip {
            get {
                return ResourceManager.GetString("Spec_DruidTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementalist.
        /// </summary>
        internal static string Spec_Elementalist {
            get {
                return ResourceManager.GetString("Spec_Elementalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player recieves +1 bonus to Fire, Water, Air, Earth and Death.
        /// </summary>
        internal static string Spec_ElementalistTip {
            get {
                return ResourceManager.GetString("Spec_ElementalistTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice lord.
        /// </summary>
        internal static string Spec_IceLord {
            get {
                return ResourceManager.GetString("Spec_IceLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player recieves +2 bonus to his water element power and deals 1 damage to random opponent&apos;s creature every turn. Additional cards: Astral guard, Merfolk overloard.
        /// </summary>
        internal static string Spec_IceLordTip {
            get {
                return ResourceManager.GetString("Spec_IceLordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromancer.
        /// </summary>
        internal static string Spec_Necromancer {
            get {
                return ResourceManager.GetString("Spec_Necromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player gains +4 health points when creatures die. Additional cards: Vampire, Drain souls.
        /// </summary>
        internal static string Spec_NecromancerTip {
            get {
                return ResourceManager.GetString("Spec_NecromancerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyromancer.
        /// </summary>
        internal static string Spec_Pyromancer {
            get {
                return ResourceManager.GetString("Spec_Pyromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player recieves +2 bonus to his fire element power and all opponent&apos;s creatures gain 2 damage when summoning. Additional cards: Armageddon, Dragon.
        /// </summary>
        internal static string Spec_PyromancerTip {
            get {
                return ResourceManager.GetString("Spec_PyromancerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stormbringer.
        /// </summary>
        internal static string Spec_Stormbringer {
            get {
                return ResourceManager.GetString("Spec_Stormbringer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player recieves +2 bonus to his air element power and starts with Griffin creature. Additional cards: Titan, Phoenix.
        /// </summary>
        internal static string Spec_StormbringerTip {
            get {
                return ResourceManager.GetString("Spec_StormbringerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization:.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} spell, cost: {1}..
        /// </summary>
        internal static string SpellShortDesc {
            get {
                return ResourceManager.GetString("SpellShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell. Cost: {0}.
        /// </summary>
        internal static string SpellShortDesc2 {
            get {
                return ResourceManager.GetString("SpellShortDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is summoning {1}.
        /// </summary>
        internal static string Summoning {
            get {
                return ResourceManager.GetString("Summoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap.
        /// </summary>
        internal static string Tap {
            get {
                return ResourceManager.GetString("Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to change.
        /// </summary>
        internal static string TapToChange {
            get {
                return ResourceManager.GetString("TapToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOURNAMENT STATISTICS.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to continue....
        /// </summary>
        internal static string ToContinue {
            get {
                return ResourceManager.GetString("ToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        internal static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In tournament you should defeat 8 opponents in series to take the first place.
        /// </summary>
        internal static string TournamentDescription {
            get {
                return ResourceManager.GetString("TournamentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament mode.
        /// </summary>
        internal static string TournamentTip {
            get {
                return ResourceManager.GetString("TournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View a short tutorial.
        /// </summary>
        internal static string TutorialTip {
            get {
                return ResourceManager.GetString("TutorialTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two players.
        /// </summary>
        internal static string TwoPlayers {
            get {
                return ResourceManager.GetString("TwoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two players mode.
        /// </summary>
        internal static string TwoPlayersTip {
            get {
                return ResourceManager.GetString("TwoPlayersTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network mode.
        /// </summary>
        internal static string ViaSockets {
            get {
                return ResourceManager.GetString("ViaSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a duel through the network (p2p).
        /// </summary>
        internal static string ViaSocketsTip {
            get {
                return ResourceManager.GetString("ViaSocketsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your deck:.
        /// </summary>
        internal static string YourDeck {
            get {
                return ResourceManager.GetString("YourDeck", resourceCulture);
            }
        }
    }
}
