//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstralBattles.Strings.de_DE {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstralBattles.Strings.de_DE.de-DE", typeof(de_DE).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Spiel ist eine mobile Verison des beliebten PC-Spiels Spectromancer. Alle Kartentexte sind urheberrechlich geschützt (c) Three Donkeys LLC. Sie können mich ausserdem über jabber main@conference.jabber.uruchie.org kontaktieren..
        /// </summary>
        internal static string AboutBody {
            get {
                return ResourceManager.GetString("AboutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luft.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Beast {
            get {
                object obj = ResourceManager.GetObject("Beast", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Campaign {
            get {
                object obj = ResourceManager.GetObject("Campaign", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object CampaignTip {
            get {
                object obj = ResourceManager.GetObject("CampaignTip", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} zaubert {1}.
        /// </summary>
        internal static string Casting {
            get {
                return ResourceManager.GetString("Casting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Chaos {
            get {
                object obj = ResourceManager.GetObject("Chaos", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schließen.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string ConfigureDeck {
            get {
                return ResourceManager.GetString("ConfigureDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigung.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glückwunsch, du hast das Turnier mit dem {0} Platz beendet. Danke für´s Spielen, warte auf Astral Battles 2 mit Kampagne und Online Multiplayer!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortsetzen.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object ContinueCampaignTip {
            get {
                object obj = ResourceManager.GetObject("ContinueCampaignTip", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Runde fortsetzen.
        /// </summary>
        internal static string ContinueTip {
            get {
                return ResourceManager.GetString("ContinueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zuletzt gespieltes Turnier fortsetzen.
        /// </summary>
        internal static string ContinueTournamentTip {
            get {
                return ResourceManager.GetString("ContinueTournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Control {
            get {
                object obj = ResourceManager.GetObject("Control", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2011 Egor Bogatov.
        /// </summary>
        internal static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string CreatureShortDesc {
            get {
                return ResourceManager.GetString("CreatureShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string CreatureShortDesc2 {
            get {
                return ResourceManager.GetString("CreatureShortDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das aktuelle Turnier wird überschrieben..
        /// </summary>
        internal static string CurrentTournamentWillBeOverwritten {
            get {
                return ResourceManager.GetString("CurrentTournamentWillBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tod.
        /// </summary>
        internal static string Death {
            get {
                return ResourceManager.GetString("Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Demonic {
            get {
                object obj = ResourceManager.GetObject("Demonic", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnier Schwierigkeit.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erde.
        /// </summary>
        internal static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leicht.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portraitauwahl.
        /// </summary>
        internal static string FaceSelection {
            get {
                return ResourceManager.GetString("FaceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback senden.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fünftes Element.
        /// </summary>
        internal static string FifthElement {
            get {
                return ResourceManager.GetString("FifthElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuer.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zuletzt gespieltes Spiel wird überschrieben..
        /// </summary>
        internal static string GameWillBeOverwritten {
            get {
                return ResourceManager.GetString("GameWillBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string Goblins {
            get {
                return ResourceManager.GetString("Goblins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwer.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat {1} gezaubert.
        /// </summary>
        internal static string HasCasted {
            get {
                return ResourceManager.GetString("HasCasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat seinen Zug übersprungen.
        /// </summary>
        internal static string HasSkipped {
            get {
                return ResourceManager.GetString("HasSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat {1} gerufen.
        /// </summary>
        internal static string HasSummoned {
            get {
                return ResourceManager.GetString("HasSummoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hat gewonnen!.
        /// </summary>
        internal static string HasWon {
            get {
                return ResourceManager.GetString("HasWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Kontaktieren Sie mich wenn Sie mir mit anderen Sprachen helfen können.
        /// </summary>
        internal static string HelpImproveLanguages {
            get {
                return ResourceManager.GetString("HelpImproveLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heilig.
        /// </summary>
        internal static string Holy {
            get {
                return ResourceManager.GetString("Holy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server erstellen.
        /// </summary>
        internal static string HostAServer {
            get {
                return ResourceManager.GetString("HostAServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server für Duell erstellen.
        /// </summary>
        internal static string HostAServerTip {
            get {
                return ResourceManager.GetString("HostAServerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion.
        /// </summary>
        internal static string Illusion {
            get {
                return ResourceManager.GetString("Illusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ist Computer (K.I).
        /// </summary>
        internal static string IsComputer {
            get {
                return ResourceManager.GetString("IsComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server beitreten.
        /// </summary>
        internal static string JoinToServer {
            get {
                return ResourceManager.GetString("JoinToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server mit IP beitreten.
        /// </summary>
        internal static string JoinToServerTip {
            get {
                return ResourceManager.GetString("JoinToServerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zuletzt erstelltes Spiel laden.
        /// </summary>
        internal static string LoadGame {
            get {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zuletzt als Server erstelltes Spiel laden.
        /// </summary>
        internal static string LoadGameTip {
            get {
                return ResourceManager.GetString("LoadGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lädt….
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschine.
        /// </summary>
        internal static string Mechanical {
            get {
                return ResourceManager.GetString("Mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Name {
            get {
                object obj = ResourceManager.GetObject("Name", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name darf nicht leer sein.
        /// </summary>
        internal static string NamesShouldBeNotEmptyMessage {
            get {
                return ResourceManager.GetString("NamesShouldBeNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name sollte einzigartig sein.
        /// </summary>
        internal static string NamesShouldBeNotEqualMessage {
            get {
                return ResourceManager.GetString("NamesShouldBeNotEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object NewCampaign {
            get {
                object obj = ResourceManager.GetObject("NewCampaign", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object NewCampaignTip {
            get {
                object obj = ResourceManager.GetObject("NewCampaignTip", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Spiel.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Spiel für 2 Spieler starten.
        /// </summary>
        internal static string NewGameTip {
            get {
                return ResourceManager.GetString("NewGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Turnier.
        /// </summary>
        internal static string NewTournament {
            get {
                return ResourceManager.GetString("NewTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Turnier starten.
        /// </summary>
        internal static string NewTournamentTip {
            get {
                return ResourceManager.GetString("NewTournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächster Gegner.
        /// </summary>
        internal static string NextGame {
            get {
                return ResourceManager.GetString("NextGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächste Runde.
        /// </summary>
        internal static string NextTurn {
            get {
                return ResourceManager.GetString("NextTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, du bist am Zug!.
        /// </summary>
        internal static string NextTurnMessage {
            get {
                return ResourceManager.GetString("NextTurnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Ok {
            get {
                object obj = ResourceManager.GetObject("Ok", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot seat Modus.
        /// </summary>
        internal static string OnOneDevice {
            get {
                return ResourceManager.GetString("OnOneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Duell an einem Gerät spielen.
        /// </summary>
        internal static string OnOneDeviceTip {
            get {
                return ResourceManager.GetString("OnOneDeviceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler 1 Name:.
        /// </summary>
        internal static string Player1NameLabel {
            get {
                return ResourceManager.GetString("Player1NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler 2 Name:.
        /// </summary>
        internal static string Player2NameLabel {
            get {
                return ResourceManager.GetString("Player2NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler Name:.
        /// </summary>
        internal static string PlayersName {
            get {
                return ResourceManager.GetString("PlayersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string Resort {
            get {
                return ResourceManager.GetString("Resort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel bewerten.
        /// </summary>
        internal static string ReviewGame {
            get {
                return ResourceManager.GetString("ReviewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runde {0} hat begonnen.
        /// </summary>
        internal static string RoundStarted {
            get {
                return ResourceManager.GetString("RoundStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        internal static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magie.
        /// </summary>
        internal static string Sorcery {
            get {
                return ResourceManager.GetString("Sorcery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druide.
        /// </summary>
        internal static string Spec_Druid {
            get {
                return ResourceManager.GetString("Spec_Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler erhält +2 Bonus auf seine Erd-Element Energie und erhält +1 Leben jede Runde. Zusätzliche Karten: Meister Heiler, Steinhagel.
        /// </summary>
        internal static string Spec_DruidTip {
            get {
                return ResourceManager.GetString("Spec_DruidTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementarmagier.
        /// </summary>
        internal static string Spec_Elementalist {
            get {
                return ResourceManager.GetString("Spec_Elementalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler erhält +1 Bonus auf Feuer, Wasser, Luft, Erde und Tod.
        /// </summary>
        internal static string Spec_ElementalistTip {
            get {
                return ResourceManager.GetString("Spec_ElementalistTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eis Lord.
        /// </summary>
        internal static string Spec_IceLord {
            get {
                return ResourceManager.GetString("Spec_IceLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler erhält +2 Bonus auf seine Wasser-Element Energie und gibt einer zufälligen gegnerische Kreatur 1 Schaden. Zusätzliche Karten: Astral Wächter, Melfolk Overlord.
        /// </summary>
        internal static string Spec_IceLordTip {
            get {
                return ResourceManager.GetString("Spec_IceLordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geisterbeschwörer.
        /// </summary>
        internal static string Spec_Necromancer {
            get {
                return ResourceManager.GetString("Spec_Necromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler erhält +4 Lebenspunkte wenn Kreaturen Sterben. Zusätzliche Karten: Vampir, Seelenstehler.
        /// </summary>
        internal static string Spec_NecromancerTip {
            get {
                return ResourceManager.GetString("Spec_NecromancerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuerbeschwörer.
        /// </summary>
        internal static string Spec_Pyromancer {
            get {
                return ResourceManager.GetString("Spec_Pyromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler erhält +2 Bonus auf seine Feuer-Element Energie und alle gegnerischen Kreaturen erhalten 2 Schaden bei Beschwörungen. Zusätzliche Karten: Armageddon, Drache.
        /// </summary>
        internal static string Spec_PyromancerTip {
            get {
                return ResourceManager.GetString("Spec_PyromancerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sturmbringer.
        /// </summary>
        internal static string Spec_Stormbringer {
            get {
                return ResourceManager.GetString("Spec_Stormbringer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler erhält +2 Bonus auf seine Luft-Element Energie und startet mit Greif Kreatur. Zusätzliche Karten: Titan, Phoenix.
        /// </summary>
        internal static string Spec_StormbringerTip {
            get {
                return ResourceManager.GetString("Spec_StormbringerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spezialisierung.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string SpellShortDesc {
            get {
                return ResourceManager.GetString("SpellShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string SpellShortDesc2 {
            get {
                return ResourceManager.GetString("SpellShortDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ruft {1}.
        /// </summary>
        internal static string Summoning {
            get {
                return ResourceManager.GetString("Summoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tippen.
        /// </summary>
        internal static string Tap {
            get {
                return ResourceManager.GetString("Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object TapToChange {
            get {
                object obj = ResourceManager.GetObject("TapToChange", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnier Statistik.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to um Fortzufahren….
        /// </summary>
        internal static string ToContinue {
            get {
                return ResourceManager.GetString("ToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnier.
        /// </summary>
        internal static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Turnier wirst du gegen 8 Gegner in folge kämpfen um den ersten Platz zu erreichen.
        /// </summary>
        internal static string TournamentDescription {
            get {
                return ResourceManager.GetString("TournamentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turniermodus.
        /// </summary>
        internal static string TournamentTip {
            get {
                return ResourceManager.GetString("TournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein kurzes tutorial ansehen.
        /// </summary>
        internal static string TutorialTip {
            get {
                return ResourceManager.GetString("TutorialTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei Spieler.
        /// </summary>
        internal static string TwoPlayers {
            get {
                return ResourceManager.GetString("TwoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei Spieler Modus.
        /// </summary>
        internal static string TwoPlayersTip {
            get {
                return ResourceManager.GetString("TwoPlayersTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzwerkmodus.
        /// </summary>
        internal static string ViaSockets {
            get {
                return ResourceManager.GetString("ViaSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel ein Duell über das Netzwerk (PvP).
        /// </summary>
        internal static string ViaSocketsTip {
            get {
                return ResourceManager.GetString("ViaSocketsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasser.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string YourDeck {
            get {
                return ResourceManager.GetString("YourDeck", resourceCulture);
            }
        }
    }
}
