//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstralBattles.Strings.fr_FR {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstralBattles.Strings.fr_FR.fr-FR", typeof(fr_FR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce jeu est une version mobile du fameux jeu de bureau Spectromancer. Tous les textes des cartes sont copyright (c) Three Donkeys LLC.
        /// </summary>
        internal static string AboutBody {
            get {
                return ResourceManager.GetString("AboutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bêtes.
        /// </summary>
        internal static string Beast {
            get {
                return ResourceManager.GetString("Beast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campagne.
        /// </summary>
        internal static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Campagne.
        /// </summary>
        internal static string CampaignTip {
            get {
                return ResourceManager.GetString("CampaignTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lance {1}.
        /// </summary>
        internal static string Casting {
            get {
                return ResourceManager.GetString("Casting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos.
        /// </summary>
        internal static string Chaos {
            get {
                return ResourceManager.GetString("Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurer deck.
        /// </summary>
        internal static string ConfigureDeck {
            get {
                return ResourceManager.GetString("ConfigureDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Félicitations, vous avez fini le Tournoi à la {0}e place. Merci d&apos;avoir joué et attendez Astral Battles 2 avec une Campagne et un multijoueur online!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer la campagne en cours.
        /// </summary>
        internal static string ContinueCampaignTip {
            get {
                return ResourceManager.GetString("ContinueCampaignTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer la partie en cours.
        /// </summary>
        internal static string ContinueTip {
            get {
                return ResourceManager.GetString("ContinueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer le dernier tournoi joué.
        /// </summary>
        internal static string ContinueTournamentTip {
            get {
                return ResourceManager.GetString("ContinueTournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2011 Egor Bogatov.
        /// </summary>
        internal static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créature ({0}), Attaque: {1}, Santé: {2}, Coût: {3}..
        /// </summary>
        internal static string CreatureShortDesc {
            get {
                return ResourceManager.GetString("CreatureShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaque: {0}, Santé: {1}, Coût: {2}..
        /// </summary>
        internal static string CreatureShortDesc2 {
            get {
                return ResourceManager.GetString("CreatureShortDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le tournoi en cours sera écrasé.
        /// </summary>
        internal static string CurrentTournamentWillBeOverwritten {
            get {
                return ResourceManager.GetString("CurrentTournamentWillBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mort.
        /// </summary>
        internal static string Death {
            get {
                return ResourceManager.GetString("Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démons.
        /// </summary>
        internal static string Demonic {
            get {
                return ResourceManager.GetString("Demonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulté du Tournoi.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terre.
        /// </summary>
        internal static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facile.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionnez un Avatar.
        /// </summary>
        internal static string FaceSelection {
            get {
                return ResourceManager.GetString("FaceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacter l&apos;auteur.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5ème élément.
        /// </summary>
        internal static string FifthElement {
            get {
                return ResourceManager.GetString("FifthElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feu.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le dernier match joué sera écrasé..
        /// </summary>
        internal static string GameWillBeOverwritten {
            get {
                return ResourceManager.GetString("GameWillBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Goblins {
            get {
                object obj = ResourceManager.GetObject("Goblins", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficile.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a lancé le sort {1}.
        /// </summary>
        internal static string HasCasted {
            get {
                return ResourceManager.GetString("HasCasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a passé son tour.
        /// </summary>
        internal static string HasSkipped {
            get {
                return ResourceManager.GetString("HasSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a invoqué un(e) {1}.
        /// </summary>
        internal static string HasSummoned {
            get {
                return ResourceManager.GetString("HasSummoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a gagné!.
        /// </summary>
        internal static string HasWon {
            get {
                return ResourceManager.GetString("HasWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactez moi si vous pouvez aider avec d&apos;autres langues.
        /// </summary>
        internal static string HelpImproveLanguages {
            get {
                return ResourceManager.GetString("HelpImproveLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacré.
        /// </summary>
        internal static string Holy {
            get {
                return ResourceManager.GetString("Holy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Héberger un serveur.
        /// </summary>
        internal static string HostAServer {
            get {
                return ResourceManager.GetString("HostAServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Héberger un serveur pour un Duel.
        /// </summary>
        internal static string HostAServerTip {
            get {
                return ResourceManager.GetString("HostAServerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion.
        /// </summary>
        internal static string Illusion {
            get {
                return ResourceManager.GetString("Illusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinateur (I.A.).
        /// </summary>
        internal static string IsComputer {
            get {
                return ResourceManager.GetString("IsComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre un serveur.
        /// </summary>
        internal static string JoinToServer {
            get {
                return ResourceManager.GetString("JoinToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre un serveur par IP.
        /// </summary>
        internal static string JoinToServerTip {
            get {
                return ResourceManager.GetString("JoinToServerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger le dernier match hébergé.
        /// </summary>
        internal static string LoadGame {
            get {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger le dernier match hébergé en tant que serveur.
        /// </summary>
        internal static string LoadGameTip {
            get {
                return ResourceManager.GetString("LoadGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement….
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mécanique.
        /// </summary>
        internal static string Mechanical {
            get {
                return ResourceManager.GetString("Mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les noms ne doivent pas être vides.
        /// </summary>
        internal static string NamesShouldBeNotEmptyMessage {
            get {
                return ResourceManager.GetString("NamesShouldBeNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les noms doivent être uniques.
        /// </summary>
        internal static string NamesShouldBeNotEqualMessage {
            get {
                return ResourceManager.GetString("NamesShouldBeNotEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle campagne.
        /// </summary>
        internal static string NewCampaign {
            get {
                return ResourceManager.GetString("NewCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencer une nouvelle campagne.
        /// </summary>
        internal static string NewCampaignTip {
            get {
                return ResourceManager.GetString("NewCampaignTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau jeu.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencer un match pour 2 joueurs.
        /// </summary>
        internal static string NewGameTip {
            get {
                return ResourceManager.GetString("NewGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau Tournoi.
        /// </summary>
        internal static string NewTournament {
            get {
                return ResourceManager.GetString("NewTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencer un nouveau tournoi.
        /// </summary>
        internal static string NewTournamentTip {
            get {
                return ResourceManager.GetString("NewTournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match suivant.
        /// </summary>
        internal static string NextGame {
            get {
                return ResourceManager.GetString("NextGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour suivant.
        /// </summary>
        internal static string NextTurn {
            get {
                return ResourceManager.GetString("NextTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, c&apos;est votre tour!.
        /// </summary>
        internal static string NextTurnMessage {
            get {
                return ResourceManager.GetString("NextTurnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode Hot Seat.
        /// </summary>
        internal static string OnOneDevice {
            get {
                return ResourceManager.GetString("OnOneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouer un Duel sur un seul appareil.
        /// </summary>
        internal static string OnOneDeviceTip {
            get {
                return ResourceManager.GetString("OnOneDeviceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du joueur 1:.
        /// </summary>
        internal static string Player1NameLabel {
            get {
                return ResourceManager.GetString("Player1NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du joueur 2:.
        /// </summary>
        internal static string Player2NameLabel {
            get {
                return ResourceManager.GetString("Player2NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du joueur:.
        /// </summary>
        internal static string PlayersName {
            get {
                return ResourceManager.GetString("PlayersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trier.
        /// </summary>
        internal static string Resort {
            get {
                return ResourceManager.GetString("Resort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noter le jeu.
        /// </summary>
        internal static string ReviewGame {
            get {
                return ResourceManager.GetString("ReviewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le tour {0} a commencé.
        /// </summary>
        internal static string RoundStarted {
            get {
                return ResourceManager.GetString("RoundStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        internal static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcellerie.
        /// </summary>
        internal static string Sorcery {
            get {
                return ResourceManager.GetString("Sorcery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sons.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druide.
        /// </summary>
        internal static string Spec_Druid {
            get {
                return ResourceManager.GetString("Spec_Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le joueur reçoit un bonus de +2 à son élément Terre et gagne +1 point de santé à chaque tour. Cartes additionelles : Maître guerisseur, Pluie de rochers.
        /// </summary>
        internal static string Spec_DruidTip {
            get {
                return ResourceManager.GetString("Spec_DruidTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elémentaliste.
        /// </summary>
        internal static string Spec_Elementalist {
            get {
                return ResourceManager.GetString("Spec_Elementalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le joueur reçoit un bonus de +1 aux éléments Feu, Eau, Air, Terre et Mort.
        /// </summary>
        internal static string Spec_ElementalistTip {
            get {
                return ResourceManager.GetString("Spec_ElementalistTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seigneur du froid.
        /// </summary>
        internal static string Spec_IceLord {
            get {
                return ResourceManager.GetString("Spec_IceLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le joueur reçoit un bonus de +2 à son élément Eau et inflige 1 dégât aléatoirement à une créature de son adversaire à chaque tour. Cartes additionelles : Guardien Astral, Suzerin Ondin.
        /// </summary>
        internal static string Spec_IceLordTip {
            get {
                return ResourceManager.GetString("Spec_IceLordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nécromancien.
        /// </summary>
        internal static string Spec_Necromancer {
            get {
                return ResourceManager.GetString("Spec_Necromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le joueur gagne +4 points de santé lorsqu&apos;une créature meurt. Cartes additionelles : Vampire, Drainer les âmes.
        /// </summary>
        internal static string Spec_NecromancerTip {
            get {
                return ResourceManager.GetString("Spec_NecromancerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyromancien.
        /// </summary>
        internal static string Spec_Pyromancer {
            get {
                return ResourceManager.GetString("Spec_Pyromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le joueur reçoit un bonus de +2 à son élément Feu et toutes les créatures de l&apos;adversaire subissent 2 dommages à l&apos;invocation. Cartes additionelles : Armageddon, Dragon.
        /// </summary>
        internal static string Spec_PyromancerTip {
            get {
                return ResourceManager.GetString("Spec_PyromancerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Héraut de la Tempête.
        /// </summary>
        internal static string Spec_Stormbringer {
            get {
                return ResourceManager.GetString("Spec_Stormbringer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le joueur reçoit un bonus de +2 à son élément Air et commence avec la créature Griffon. Cartes additionelles : Titan, Phoenix.
        /// </summary>
        internal static string Spec_StormbringerTip {
            get {
                return ResourceManager.GetString("Spec_StormbringerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécialisation:.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ({0}), coût: {1}.
        /// </summary>
        internal static string SpellShortDesc {
            get {
                return ResourceManager.GetString("SpellShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort. Coût: {0}..
        /// </summary>
        internal static string SpellShortDesc2 {
            get {
                return ResourceManager.GetString("SpellShortDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} invoque {1}.
        /// </summary>
        internal static string Summoning {
            get {
                return ResourceManager.GetString("Summoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez.
        /// </summary>
        internal static string Tap {
            get {
                return ResourceManager.GetString("Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez pour modifier.
        /// </summary>
        internal static string TapToChange {
            get {
                return ResourceManager.GetString("TapToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATISTIQUES DU TOURNOI.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pour continuer….
        /// </summary>
        internal static string ToContinue {
            get {
                return ResourceManager.GetString("ToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournoi.
        /// </summary>
        internal static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dans un Tournoi, vous serez opposé à 8 adversaires pour obtenir la 1ère place.
        /// </summary>
        internal static string TournamentDescription {
            get {
                return ResourceManager.GetString("TournamentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Tournoi.
        /// </summary>
        internal static string TournamentTip {
            get {
                return ResourceManager.GetString("TournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutoriel.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir un court tutoriel.
        /// </summary>
        internal static string TutorialTip {
            get {
                return ResourceManager.GetString("TutorialTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deux joueurs.
        /// </summary>
        internal static string TwoPlayers {
            get {
                return ResourceManager.GetString("TwoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode deux joueurs.
        /// </summary>
        internal static string TwoPlayersTip {
            get {
                return ResourceManager.GetString("TwoPlayersTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Réseau.
        /// </summary>
        internal static string ViaSockets {
            get {
                return ResourceManager.GetString("ViaSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faire un duel en Réseau (p2p).
        /// </summary>
        internal static string ViaSocketsTip {
            get {
                return ResourceManager.GetString("ViaSocketsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eau.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre deck:.
        /// </summary>
        internal static string YourDeck {
            get {
                return ResourceManager.GetString("YourDeck", resourceCulture);
            }
        }
    }
}
