//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstralBattles.Strings.ru_RU {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstralBattles.Strings.ru_RU.ru-RU", typeof(ru_RU).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to об игре.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта игра является мобильной версией десктопной игры Спектромансер. Все тексты карт в игре - собственность (c) Three Donkeys LLC. Вы так же можете связаться со мной через jabber в main@conference.jabber.uruchie.org.
        /// </summary>
        internal static string AboutBody {
            get {
                return ResourceManager.GetString("AboutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воздух.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звери.
        /// </summary>
        internal static string Beast {
            get {
                return ResourceManager.GetString("Beast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания.
        /// </summary>
        internal static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим компании.
        /// </summary>
        internal static string CampaignTip {
            get {
                return ResourceManager.GetString("CampaignTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} колдует {1}.
        /// </summary>
        internal static string Casting {
            get {
                return ResourceManager.GetString("Casting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хаос.
        /// </summary>
        internal static string Chaos {
            get {
                return ResourceManager.GetString("Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настроить колоду.
        /// </summary>
        internal static string ConfigureDeck {
            get {
                return ResourceManager.GetString("ConfigureDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! вы закончили турнир на {0} месте. Спасибо за игру, надеюсь, вы получили удовольствие и не поленитесь поставить 5ку - это поспособствует скорейшему выходу Astral Battles 2 с большой и интересной компанией..
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить начатую компанию.
        /// </summary>
        internal static string ContinueCampaignTip {
            get {
                return ResourceManager.GetString("ContinueCampaignTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить последнюю игру.
        /// </summary>
        internal static string ContinueTip {
            get {
                return ResourceManager.GetString("ContinueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить турнир.
        /// </summary>
        internal static string ContinueTournamentTip {
            get {
                return ResourceManager.GetString("ContinueTournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроль.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2011 Богатов Егор.
        /// </summary>
        internal static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стихия: {0}, атака: {1}, здоровье: {2}, цена: {3}..
        /// </summary>
        internal static string CreatureShortDesc {
            get {
                return ResourceManager.GetString("CreatureShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атака: {0}, здоровье: {1}, цена: {2}..
        /// </summary>
        internal static string CreatureShortDesc2 {
            get {
                return ResourceManager.GetString("CreatureShortDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты прошлого турнира будут потеряны..
        /// </summary>
        internal static string CurrentTournamentWillBeOverwritten {
            get {
                return ResourceManager.GetString("CurrentTournamentWillBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смерть.
        /// </summary>
        internal static string Death {
            get {
                return ResourceManager.GetString("Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демоны.
        /// </summary>
        internal static string Demonic {
            get {
                return ResourceManager.GetString("Demonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сложность турнира.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Земля.
        /// </summary>
        internal static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легко.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор аватара.
        /// </summary>
        internal static string FaceSelection {
            get {
                return ResourceManager.GetString("FaceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратная связь.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5ая стихия.
        /// </summary>
        internal static string FifthElement {
            get {
                return ResourceManager.GetString("FifthElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Огонь.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последняя недоиграная игра будет перезатёрта.
        /// </summary>
        internal static string GameWillBeOverwritten {
            get {
                return ResourceManager.GetString("GameWillBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гоблины.
        /// </summary>
        internal static string Goblins {
            get {
                return ResourceManager.GetString("Goblins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тяжело.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} вызвал заклинание {1}.
        /// </summary>
        internal static string HasCasted {
            get {
                return ResourceManager.GetString("HasCasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} пропускает ход.
        /// </summary>
        internal static string HasSkipped {
            get {
                return ResourceManager.GetString("HasSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} вызывает {1}.
        /// </summary>
        internal static string HasSummoned {
            get {
                return ResourceManager.GetString("HasSummoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} побеждает!.
        /// </summary>
        internal static string HasWon {
            get {
                return ResourceManager.GetString("HasWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Свяжитесь со мной, если хотите помочь с переводом.
        /// </summary>
        internal static string HelpImproveLanguages {
            get {
                return ResourceManager.GetString("HelpImproveLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Святость.
        /// </summary>
        internal static string Holy {
            get {
                return ResourceManager.GetString("Holy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер.
        /// </summary>
        internal static string HostAServer {
            get {
                return ResourceManager.GetString("HostAServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захостить сервер.
        /// </summary>
        internal static string HostAServerTip {
            get {
                return ResourceManager.GetString("HostAServerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иллюзии.
        /// </summary>
        internal static string Illusion {
            get {
                return ResourceManager.GetString("Illusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компьютер (ИИ).
        /// </summary>
        internal static string IsComputer {
            get {
                return ResourceManager.GetString("IsComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединиться.
        /// </summary>
        internal static string JoinToServer {
            get {
                return ResourceManager.GetString("JoinToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединиться к серверу по IP.
        /// </summary>
        internal static string JoinToServerTip {
            get {
                return ResourceManager.GetString("JoinToServerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить игру.
        /// </summary>
        internal static string LoadGame {
            get {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить игру в качестве сервера.
        /// </summary>
        internal static string LoadGameTip {
            get {
                return ResourceManager.GetString("LoadGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to игра.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Механика.
        /// </summary>
        internal static string Mechanical {
            get {
                return ResourceManager.GetString("Mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена должны быть заполнены.
        /// </summary>
        internal static string NamesShouldBeNotEmptyMessage {
            get {
                return ResourceManager.GetString("NamesShouldBeNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена должны быть разными.
        /// </summary>
        internal static string NamesShouldBeNotEqualMessage {
            get {
                return ResourceManager.GetString("NamesShouldBeNotEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая компания.
        /// </summary>
        internal static string NewCampaign {
            get {
                return ResourceManager.GetString("NewCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать новую компанию.
        /// </summary>
        internal static string NewCampaignTip {
            get {
                return ResourceManager.GetString("NewCampaignTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая игра.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать новую игру на двоих игроков.
        /// </summary>
        internal static string NewGameTip {
            get {
                return ResourceManager.GetString("NewGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый турнир.
        /// </summary>
        internal static string NewTournament {
            get {
                return ResourceManager.GetString("NewTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать новый турнир.
        /// </summary>
        internal static string NewTournamentTip {
            get {
                return ResourceManager.GetString("NewTournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующая.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующая игра.
        /// </summary>
        internal static string NextGame {
            get {
                return ResourceManager.GetString("NextGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий ход.
        /// </summary>
        internal static string NextTurn {
            get {
                return ResourceManager.GetString("NextTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, твой ход, не спи!.
        /// </summary>
        internal static string NextTurnMessage {
            get {
                return ResourceManager.GetString("NextTurnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормально.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окей.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим хот-сит.
        /// </summary>
        internal static string OnOneDevice {
            get {
                return ResourceManager.GetString("OnOneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра дуэли на одном устройстве.
        /// </summary>
        internal static string OnOneDeviceTip {
            get {
                return ResourceManager.GetString("OnOneDeviceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to опции.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя игрока 1:.
        /// </summary>
        internal static string Player1NameLabel {
            get {
                return ResourceManager.GetString("Player1NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя игрока 2:.
        /// </summary>
        internal static string Player2NameLabel {
            get {
                return ResourceManager.GetString("Player2NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя игрока:.
        /// </summary>
        internal static string PlayersName {
            get {
                return ResourceManager.GetString("PlayersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресорт.
        /// </summary>
        internal static string Resort {
            get {
                return ResourceManager.GetString("Resort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставить оценку.
        /// </summary>
        internal static string ReviewGame {
            get {
                return ResourceManager.GetString("ReviewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало раунда {0}.
        /// </summary>
        internal static string RoundStarted {
            get {
                return ResourceManager.GetString("RoundStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слот.
        /// </summary>
        internal static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чары.
        /// </summary>
        internal static string Sorcery {
            get {
                return ResourceManager.GetString("Sorcery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звуки.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Древолюб.
        /// </summary>
        internal static string Spec_Druid {
            get {
                return ResourceManager.GetString("Spec_Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок получает +2 бонус к его силе земли и +1 здоровья каждый ход. Дополнительные карты: Верховный целитель, Каменный дождь.
        /// </summary>
        internal static string Spec_DruidTip {
            get {
                return ResourceManager.GetString("Spec_DruidTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элементалист.
        /// </summary>
        internal static string Spec_Elementalist {
            get {
                return ResourceManager.GetString("Spec_Elementalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок получает +1 ко всем стихиям..
        /// </summary>
        internal static string Spec_ElementalistTip {
            get {
                return ResourceManager.GetString("Spec_ElementalistTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водянник.
        /// </summary>
        internal static string Spec_IceLord {
            get {
                return ResourceManager.GetString("Spec_IceLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок получает +2 бонус к его силе воды и наносит 1 урона случайному существу противника каждый ход. Дополнительные карты: Астральные страж,  Мерфолк предводитель.
        /// </summary>
        internal static string Spec_IceLordTip {
            get {
                return ResourceManager.GetString("Spec_IceLordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некромансёр.
        /// </summary>
        internal static string Spec_Necromancer {
            get {
                return ResourceManager.GetString("Spec_Necromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок получает +4 к здоровью, когда кто-либо умирает. Дополнительные карты: Вампир, Извлечение душ.
        /// </summary>
        internal static string Spec_NecromancerTip {
            get {
                return ResourceManager.GetString("Spec_NecromancerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пироманьяк.
        /// </summary>
        internal static string Spec_Pyromancer {
            get {
                return ResourceManager.GetString("Spec_Pyromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок получает +2 бонус к его силе огня и наносит 2 урона всем существам противника в момент призыва. Дополнительные карты: Дракон, Армагеддон.
        /// </summary>
        internal static string Spec_PyromancerTip {
            get {
                return ResourceManager.GetString("Spec_PyromancerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воздушник.
        /// </summary>
        internal static string Spec_Stormbringer {
            get {
                return ResourceManager.GetString("Spec_Stormbringer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок получает +2 бонус к его силе воздуха и начинает игру с грифоном в первом слоте. Дополнительные карты: Титан, Феникс.
        /// </summary>
        internal static string Spec_StormbringerTip {
            get {
                return ResourceManager.GetString("Spec_StormbringerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специализация:.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заклинание, стихия: {0}, стоимость: {1}..
        /// </summary>
        internal static string SpellShortDesc {
            get {
                return ResourceManager.GetString("SpellShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заклинание. Стоимость: {0}..
        /// </summary>
        internal static string SpellShortDesc2 {
            get {
                return ResourceManager.GetString("SpellShortDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} вызывает {1}.
        /// </summary>
        internal static string Summoning {
            get {
                return ResourceManager.GetString("Summoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щёлкните,.
        /// </summary>
        internal static string Tap {
            get {
                return ResourceManager.GetString("Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        internal static string TapToChange {
            get {
                return ResourceManager.GetString("TapToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СТАТИСТИКА ТУРНИРА.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  чтобы продолжить.
        /// </summary>
        internal static string ToContinue {
            get {
                return ResourceManager.GetString("ToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турнир.
        /// </summary>
        internal static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В турнире вы сражаетесь с 8 противниками поочередно.
        /// </summary>
        internal static string TournamentDescription {
            get {
                return ResourceManager.GetString("TournamentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим турнира.
        /// </summary>
        internal static string TournamentTip {
            get {
                return ResourceManager.GetString("TournamentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Туториал.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть короткий туториал (eng).
        /// </summary>
        internal static string TutorialTip {
            get {
                return ResourceManager.GetString("TutorialTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два игрока.
        /// </summary>
        internal static string TwoPlayers {
            get {
                return ResourceManager.GetString("TwoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра вдвоём на одном устройстве.
        /// </summary>
        internal static string TwoPlayersTip {
            get {
                return ResourceManager.GetString("TwoPlayersTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра по сети.
        /// </summary>
        internal static string ViaSockets {
            get {
                return ResourceManager.GetString("ViaSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра по сети на двух устройствах.
        /// </summary>
        internal static string ViaSocketsTip {
            get {
                return ResourceManager.GetString("ViaSocketsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрация.
        /// </summary>
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вода.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вы.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша колода:.
        /// </summary>
        internal static string YourDeck {
            get {
                return ResourceManager.GetString("YourDeck", resourceCulture);
            }
        }
    }
}
